"""empty message

Revision ID: 0b6d24f2db57
Revises: 63f398742309
Create Date: 2020-07-17 16:44:18.194045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6d24f2db57'
down_revision = '63f398742309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'password')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'users', ['user_id'], ['password_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'users', ['user_id'], ['id'])
    op.add_column('role', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
