"""empty message

Revision ID: 5802edd44cb0
Revises: 0b6d24f2db57
Create Date: 2020-07-17 17:20:58.690949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5802edd44cb0'
down_revision = '0b6d24f2db57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'password')
    op.drop_column('role', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.add_column('role', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
