"""empty message

Revision ID: 63f398742309
Revises: da70944e7305
Create Date: 2020-07-17 16:43:51.605878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f398742309'
down_revision = 'da70944e7305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
